/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simulador.de.processos;

import javax.swing.JOptionPane;

/**
 *
 * @author andre
 */
public class InserirProcesso extends javax.swing.JDialog {

    /**
     * Creates new form InserirProcesso
     */
    public InserirProcesso(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    private String jnome;
    private int jPID;
    private int i =1;
    private int jTchegada;
    private int jCiclos;
    private int jPrioridade;
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        INBTCancelar = new javax.swing.JButton();
        INBTAdicionar = new javax.swing.JButton();
        INTChegada = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        INPid = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        INCCPU = new javax.swing.JFormattedTextField();
        INSNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSliderPrioridade = new javax.swing.JSlider();
        jLabelprioridade = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                formWindowDeactivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        INBTCancelar.setBackground(new java.awt.Color(153, 0, 0));
        INBTCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        INBTCancelar.setText("Cancelar");
        INBTCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INBTCancelarActionPerformed(evt);
            }
        });

        INBTAdicionar.setBackground(new java.awt.Color(51, 153, 0));
        INBTAdicionar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        INBTAdicionar.setText("Adicionar");
        INBTAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INBTAdicionarActionPerformed(evt);
            }
        });

        INTChegada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        INTChegada.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        INTChegada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INTChegadaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("PID");

        INPid.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#000"))));
        INPid.setText("1");
        INPid.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nome");

        INCCPU.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        INCCPU.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        INSNome.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Ciclos de CPU");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Tempo de Chegada");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Prioridade");

        jSliderPrioridade.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderPrioridadeStateChanged(evt);
            }
        });

        jLabelprioridade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelprioridade.setText("5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(315, Short.MAX_VALUE)
                .addComponent(INTChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(INPid, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(40, 40, 40)
                            .addComponent(jLabel4))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(4, 4, 4)
                            .addComponent(INSNome, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(jLabel3)
                            .addGap(19, 19, 19)
                            .addComponent(INCCPU, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(28, 28, 28)
                            .addComponent(jLabelprioridade))
                        .addComponent(jSliderPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addComponent(INBTAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)
                            .addComponent(INBTCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(INTChegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addComponent(jLabel1))
                        .addComponent(INPid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel4)))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(jLabel2))
                        .addComponent(INSNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addComponent(jLabel3))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addComponent(INCCPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(17, 17, 17)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabelprioridade))
                    .addGap(5, 5, 5)
                    .addComponent(jSliderPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(INBTAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(INBTCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void INBTAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INBTAdicionarActionPerformed
        // TODO add your handling code here:

        //int pid = Integer.parseInt(INPid.getText());
        //int vprioridade = Integer.parseInt(jLabelprioridade.getText());
        //int tchegada = Integer.parseInt(INTChegada.getText());
        //int ciclocpu = Integer.parseInt(INCCPU.getText());

        //JFrame parent;
        //parent = (JFrame)this.getRootPane().getParent();

        //parent = new TelaPrincipal();
        //parent.setVisible(true);
        //parent.inserirProcessoTabela(pid, INSNome.getText(), vprioridade, tchegada, ciclocpu, 0, 0);

        
       
        if("".equals(INSNome.getText())|INCCPU.getValue() == null){
            JOptionPane.showMessageDialog(null, "Preecha todos os campos!");
            INSNome.requestFocus();
        }else{
        
       this.jnome = INSNome.getText();
       this.jCiclos = Integer.parseInt(INCCPU.getValue().toString());
       this.jPID = Integer.parseInt(INPid.getValue().toString());
       this.jPrioridade = Integer.parseInt(jLabelprioridade.getText());
       this.jTchegada = Integer.parseInt(INTChegada.getValue().toString());
        
        INPid.setValue(jPID+1);
        
        
        INSNome.setText(""); this.dispose();}
        
        
      

    }//GEN-LAST:event_INBTAdicionarActionPerformed

    private void jSliderPrioridadeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderPrioridadeStateChanged
        // TODO add your handling code here:

        try {
            jLabelprioridade.setText((String.valueOf(jSliderPrioridade.getValue() / 10)));
        } catch (Exception e) {

        }
    }//GEN-LAST:event_jSliderPrioridadeStateChanged

    private void INBTCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INBTCancelarActionPerformed
        // TODO add your handling code here:
        this.jnome = null;
        this.dispose();
    }//GEN-LAST:event_INBTCancelarActionPerformed

    private void INTChegadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INTChegadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INTChegadaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        INTChegada.requestFocus();
        INSNome.requestFocus();
        
        
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void formWindowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowDeactivated
        // TODO add your handling code here:
        
        
        INTChegada.setValue(INPid.getValue());
        
    }//GEN-LAST:event_formWindowDeactivated

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InserirProcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InserirProcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InserirProcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InserirProcesso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                InserirProcesso dialog = new InserirProcesso(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton INBTAdicionar;
    private javax.swing.JButton INBTCancelar;
    private javax.swing.JFormattedTextField INCCPU;
    private javax.swing.JFormattedTextField INPid;
    private javax.swing.JTextField INSNome;
    private javax.swing.JFormattedTextField INTChegada;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelprioridade;
    private javax.swing.JSlider jSliderPrioridade;
    // End of variables declaration//GEN-END:variables

    public String getJnome() {
        return jnome;
    }

    public void setJnome(String jnome) {
        this.jnome = jnome;
    }

    public int getjPID() {
        return jPID;
    }

    public void setjPID(int jPID) {
        this.jPID = jPID;
    }

    public int getjTchegada() {
        return jTchegada;
    }

    public void setjTchegada(int jTchegada) {
        this.jTchegada = jTchegada;
    }

    public int getjCiclos() {
        return jCiclos;
    }

    public void setjCiclos(int jCiclos) {
        this.jCiclos = jCiclos;
    }

    public int getjPrioridade() {
        return jPrioridade;
    }

    public void setjPrioridade(int jPrioridade) {
        this.jPrioridade = jPrioridade;
    }
}
